drager/wasm-pack

Cargo.lock, Cargo.toml, src/bindgen.rs, src/build.rs, src/lib.rs, src/main.rs, src/manifest.rs, src/progressbar.rs
=> fix(style): improve output messaging

README.md, src/bindgen.rs
fixes #69 
Change references to wasm-bindgen from pointing at git repo to pointing at crates.io
=> Fixes issue 69 - use Cargo version of wasm-bindgen to better ensure not-broken build

src/manifest.rs, tests/fixtures/bad-cargo-toml/Cargo.lock, tests/fixtures/bad-cargo-toml/Cargo.toml, tests/fixtures/bad-cargo-toml/README.md, tests/fixtures/bad-cargo-toml/src/lib.rs
Because the toml error only spits out the error for the first thing it
runs into it doesn't parse all of the missing fields. We first serialize
the data to a generic toml type to check this ourselves. If everything
is there we serialize directly to the type we expected. Otherwise we
throw an error with all the fields that are missing.
Closes #43 
I think we should make a custom error type at some point for #12 but that would be a little outside the scope of the PR. I'd like to test with assert-cli but that's still blocked for windows, however I included a test fixture for it to eventually be added in and one that can be used to test locally. Output looks like this:
=> feat(warn): warn on all missing fields for a pkg

src/command.rs, src/lib.rs, src/main.rs, tests/manifest/main.rs
This pull request is designed to move all the functionality out of the main.rs binary and into the main library itself - for testability and to hopefully provide some help with https://github.com/ashleygwilliams/wasm-pack/issues/25 .
Currently throws warning due to line 11 in command.rs - unused import of quicli - import is used for the StructOpt derive macro, so is needed to be imported, but due to no structs/functions from quicli being usied it still throws this warning.
=> Refactor main.rs

src/bindgen.rs, src/build.rs, src/command.rs, src/main.rs, src/manifest.rs, src/npm.rs, src/readme.rs, tests/manifest/main.rs, tests/manifest/utils.rs
fixes #94 
this PR does a few things:
- adds a step to the `wasm_bindgen` run that renames the generated js file to `index.js`
- adds a `main` entry to the `package.json` that points to `index.js`
- removes the js file from the files entry since it's preservation in the package is cover by being in the `main` entry
- removes redundant/unnecessary checks on `package.json` contents in some tests
=> feat(manifest): add main entry

src/bindgen.rs, src/command.rs, src/emoji.rs, src/progressbar.rs, tests/fixtures/bad-cargo-toml/Cargo.lock, tests/fixtures/bad-cargo-toml/src/lib.rs, tests/fixtures/no-readme/Cargo.lock, tests/fixtures/scopes/Cargo.lock
the last PR to clean everything up for 0.2.0
=> pre 0.2.0 nits

src/bindgen.rs, src/manifest.rs, tests/manifest/main.rs
=> fix(bindgen): don't rename to index

src/bindgen.rs, src/build.rs, src/command.rs, src/error.rs, src/lib.rs, src/manifest.rs, src/npm.rs, src/progressbar.rs, src/readme.rs
This does two big things:
- We add custom error messages and conversions from other error types
into our own error type. This means we can create or modify more
fine grained errors rather than using whatever `failure::Error` gives
us. The first one we have is a `Cli` error, whereby calls to things
like wasm-bindgen or npm failed.
- We also make it so that `PBAR.error()` is called only on exit. We grab
a reference to whatever error gets passed up the chain, have it
generate a message to be printed as an error to PBAR, close up PBAR
like normal, and then print our actual error message to stderr!
The main benefits of this is that as long as we return an error, PBAR
will print and close itself up and we don't need to call it every time
or forget that we would need to call it, and we put error …
=> feat(error_msg): Make custom module for errors

docs/init.md, docs/pack.md, docs/prerequisites.md, docs/publish.md, docs/setup.md
This branch contains some documentation work to help close out #63. There are some short excerpts about the init, pack, and publish commands, as well as links to related documentation for certain concepts like package scoping.
I can also add a link to @mgattozzi's [existing tutorial](https://rust-lang-nursery.github.io/rust-wasm/wasm-pack/introduction.html) somewhere in here if that seems like a good idea.
___
```bash
```
=> Add example usage documentation

src/command.rs, src/npm.rs
Implements #83 
This wraps npm adduser. I’ve copied the argument descriptions from npm.
By the way: why are all sub commands marked as NOT IMPLEMENTED?
I’m a little unsure about some of the solutions I used here.
1. `if let` inside `arg()` seems wired.
2. passing 4 args down multiple times feels strange
I took the liberty to add some spacing inside the command enum, since it really confused me for a few minutes.
Does this seem okay otherwise?
Cheers!
```bash
````
=> Wrap npm adduser

src/command.rs
I noticed this while working on a different issue, and figured I would open a quick PR about it :) Currently, the output generated by running `wasm-pack --help` looks like this:
```
✨  wasm-pack --help
wasm-pack 0.2.0
Ashley Williams <ashley666ashley@gmail.com>
📦 ✨  pack and publish your wasm!
USAGE:
wasm-pack [FLAGS] <SUBCOMMAND>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
-v, --verbose    log all the things
SUBCOMMANDS:
help       Prints this message or the help of the given subcommand(s)
init       🐣  initialize a package.json based on your compiled wasm
pack       🍱  create a tar of your npm package but don't publish! [NOT IMPLEMENTED]
publish    🎆  pack up your npm package and publish! [NOT IMPLEMENTED]
```
This commit removes the "[NOT …
=> Removed 'NOT IMPLEMENTED' flags from commands that are now implemented.

src/bindgen.rs, src/command.rs, src/manifest.rs, tests/manifest/main.rs, tests/manifest/utils.rs
- relates to #107 
I got so excited about #107 as typescript user so gave a quick stab, but not sure if this change is intended scope for issue itself. Feel freely close / or suggest as needed. 🙏 
This PR intends to ask bindgen to generate typescript definition as well, also expand `NpmPackage` struct to include `types` property into `package.json`. It currently takes naïve approach by specifying type definition to same entrypoint of `main`.
```bash
```
=> feat(command): expose --no-typescript option to init command

.travis.yml
No issue existing currently, but surfaced in #125 and #127.
Travis builds are failing caused by an update in rustfmt.
The command is now according to: https://github.com/rust-lang-nursery/rustfmt#checking-style-on-a-ci-server
Let's see if it works 🤔 
```bash
```
=> Update Travis' rustfmt arguments

docs/init.md, src/bindgen.rs, src/command.rs
=> Djfarly nodejs flag

src/manifest.rs, tests/manifest/main.rs
=> Add the TypeScript definition to the published files

src/logger.rs
=> fix(logger): if no path, append wasm-pack.log to current dir

Cargo.lock, Cargo.toml
None of the boxes were applicable, this is really a minor change.
Since `human-panic` is now stable, you can just use the stable version to signal that the API won't just change :smile:
=> Bumping human-panic to 1.0.0

docs/init.md, src/bindgen.rs, src/build.rs, src/command.rs
First pass at #126 .
```bash
```
=> Add a --debug option to suppress cargo build --release.

src/command.rs, src/error.rs, src/manifest.rs, tests/fixtures/bad-cargo-toml/Cargo.toml, tests/manifest/main.rs
Checks that crate-type includes "cdylib" -- fails with an error if it does not.
Closes https://github.com/ashleygwilliams/wasm-pack/issues/140
thank you for holding the rust workshop at jsconf this past weekend @ashleygwilliams! 😄
=> check that crate type includes cdylib

src/command.rs, src/error.rs, src/manifest.rs, tests/fixtures/bad-cargo-toml/Cargo.toml, tests/manifest/main.rs
Fixes #141
I've used the same error that's about to be merged in #150 [[error.rs]](https://github.com/ashleygwilliams/wasm-pack/pull/150/files#diff-9a269209bed069ffb36d5565a91c9840R19) to avoid duplication or further refactoring.
I guess texts may have to be reviewed as I'm not a native English speaker 😉 
Any other suggestion to improve the code will be really appreciated.
=> feat(wasm_bindgen): checks wasm-bindgen declaration in Cargo.toml

docs/init.md, src/bindgen.rs, src/build.rs, src/command.rs, src/manifest.rs, src/progressbar.rs, src/readme.rs, tests/manifest/main.rs, tests/readme/main.rs
=> Add --skip-build flag for init command #144

CONTRIBUTING.md, README.md, docs/prerequisites.md
=> Fix broken links to rust-lang-nursery/rust-wasm

src/command/init.rs, src/command/mod.rs
=> feat(init): no install flag

src/manifest.rs, tests/manifest/main.rs
- [ x] You have the latest version of `rustfmt` installed and have your 
```bash
```
- [ x] You ran `rustfmt` on the code base before submitting
=> fix(mainfest): missing _bg.js file in package.json

src/command/init.rs, src/manifest.rs, tests/manifest/main.rs
fixes #199 (FOR REAL THIS TIME)
this PR does several things:
- passes the value of the target flag to the `write_package_json` method
- optionally includes a `_bg.js` file in the `files` key if the `target` is `nodejs`
- updates `files` key to NOT include the file in `main` (it is unecessary)
- adds a test to ensure correct behavior on node
- cleans up tests to test for correct `files` key
=> fix files behavior on node, and generally remove redundancy in the files key

src/bindgen.rs, src/build.rs, src/command/init.rs, src/command/mod.rs, src/command/utils.rs, src/emoji.rs, src/error.rs, src/lib.rs, src/logger.rs, src/manifest.rs, src/npm.rs, src/progressbar.rs, src/readme.rs
And add all the missing doc comments.
-------------------------------
```bash
```
=> Deny missing documentation

src/bindgen.rs, src/build.rs, src/command/init.rs, src/command/mod.rs, src/command/pack.rs, src/command/publish.rs, src/command/utils.rs, src/manifest.rs, src/readme.rs, tests/manifest/main.rs, tests/manifest/utils.rs, tests/readme/main.rs, tests/readme/utils.rs
I think this is it. I want to take another look tomorrow to validate that I didn't miss something.
Fixes #213 
```bash
```
=> Use PathBuf instead of String to handle paths

src/command/build.rs, src/command/mod.rs, src/logger.rs, src/manifest.rs, tests/all/build.rs, tests/all/main.rs, tests/fixtures/not-a-crate/README.md
=> Running in non crate dir

src/manifest.rs
=> Skip serializing empty or None values to package.json

README.md, docs/src/command/pack-and-publish.md
=> fix(doc): fix links in README

.travis.yml
Addresses #247 
1. New github deploy macro in travis
2. Deploy artifacts and book in their own job
3. Use job name environment variable
4. Copy notification settings from wasm-bindgen travis
5. Cache cargo for faster builds
---
```bash
```
=> Reorg travis deployment

src/bindgen.rs
=> tidy: Don't use double negatives

.travis.yml, Cargo.lock, Cargo.toml, src/bindgen.rs, src/command/build.rs, src/error.rs, src/lib.rs, tests/all/bindgen.rs, tests/all/main.rs, tests/all/utils/fixture.rs
=> Prefer downloading pre-built `wasm-bindgen` binaries

Cargo.lock
We use `--locked` for testing but that means occasionally we have issues where CI will seize up. I think we'll need a better solution going forward, but for now this should help with things failing. This is part of my efforts today to get CI back to green for everyone else if it's not that way already. Also cleared the cache on Travis just in case.
```bash
```
=> chore(deps) Update lockfile

.travis.yml, src/bindgen.rs, src/command/build.rs, src/command/utils.rs, src/manifest.rs, src/readme.rs, tests/all/manifest.rs, tests/all/readme.rs, tests/all/utils/manifest.rs
This PR addresses #235 
There is a new command line flag for the build command: `--out-dir` and `-d`. Supply a relative path and put your wasm somewhere else! Default is `pkg`. 
---
```bash
```
=> Specify output directory with CLI

.travis.yml
We hit the exact issues described in https://levans.fr/rust_travis_cache.html, which was why we disabled caching in the first place, but if we cache `$HOME/.cargo/bin` then that will help for our `cargo install`ed tools.
=> CI: re-enable caching for `cargo install`ed tools

src/manifest.rs
Before these changes, the CLI output would read:
[4/8] 📂  Creating a pkg directory...
[5/8] 📝  Writing a package.json...
⚠️   [WARN]: Field description is missing from Cargo.toml. It is not necessary, but recommended
⚠️   [WARN]: Field repository is missing from Cargo.toml. It is not necessary, but recommended
⚠️   [WARN]: Field license is missing from Cargo.toml. It is not necessary, but recommended
Which confused me at first glance, as I read literally that a field description was missing.  After this change, the output would be:
[4/8] 📂  Creating a pkg directory...
[5/8] 📝  Writing a package.json...
⚠️   [WARN]: Field 'description' is missing from Cargo.toml. It is not necessary, but recommended
⚠️   [WARN]: Field 'repository' is missing from Cargo.toml. It is not necessary, but …
=> Provide single quote separators around missing Cargo.toml fields to improve readability

src/npm.rs
closes #257 
I added `Stdio::inherit()` for `stdin` and `stdout` to`npm_publish` to get the CLI output from npm when a user tries to publish with otp enabled. This will allow the user to enter their otp and successfully publish their package to the registry.
Please let me know if there's any thing I need to tweak or fix!
Thanks!
---
```bash
```
=> add support for otp when publishing to npm

README.md
Update links to point to https://rustwasm.github.io/wasm-pack/ instead of the
in-tree markdown which doesn't always have working hyperlinks (but mdbook
does!). Additionally tweak some getting started code using `wasm_bindgen` as
well as removing some links no longer used.
=> Tweak some README links

.appveyor.yml
fixes #147 
It looks like Windows releases aren't getting build for wasm-pack tags
unfortunately and taking a look at the [last logs][logs] it looks like the
reason is that the `master` branch is required. I'm not actually entirely sure
what's required here but by removing this it's closer to `wasm-bindgen`'s
configuration which I think is working!
[logs]: https://ci.appveyor.com/project/ashleygwilliams/wasm-pack-071k0/build/1.0.72
=> Remove `branch: master` from AppVeyor deploy

src/command/mod.rs, src/command/publish/access.rs, src/command/publish/mod.rs, src/logger.rs, src/npm.rs
=> feat(publish): add --access flag to publish command

src/manifest/mod.rs, src/manifest/npm/commonjs.rs, src/manifest/npm/es6.rs, src/manifest/npm/esmodules.rs, src/manifest/npm/mod.rs, src/manifest/npm/repository.rs, tests/all/manifest.rs, tests/all/utils/manifest.rs
fixes #309 plus rather large refactor which is in the first few commits
strategy here is to define several struct for types of packages folks will want to make (common js only, es6 only, es6 + commonjs to start), we'll serialize the Cargo.toml into the format based on what the target specified is
=> modules modules modules

src/bindgen.rs, src/manifest/mod.rs, src/manifest/npm/mod.rs, src/manifest/npm/nomodules.rs, tests/all/manifest.rs, tests/all/utils/manifest.rs
fixes #317 
note: 
this PR puts the js file generated by bindgen in the `browser` key in `package.json` and includes it in `files`. i am not sure this is the right call- so if folks could weigh in that would be excellent.
=> support no-modules

docs/src/SUMMARY.md, docs/src/commands/index.md, docs/src/commands/init.md, docs/src/contributing.md, docs/src/getting-started/index.md, docs/src/getting-started/project-setup/index.md, docs/src/prerequisites/index.md, docs/src/tutorial/index.md
fixes #325 
Switched the links from using absolute paths to relative paths. Should now work locally served with mdBooks and when served on pages.
```bash
```
=> Fix broken links in book by replacing absolute paths with relative paths

CHANGELOG.md
- Repair a broken link in the changelog
Looks like it probably broke with https://github.com/rustwasm/wasm-bindgen/commit/2e7620e014ab53b450696529afd12e3c685221e1.
Fixes #337.
This is my first PR here; please let me know if I should tweak anything in this PR or in the related issue to be consistent with how things are done here. I'm excited about the WG-wasm roadmap and am looking forward to getting more involved!
=> fix(changelog): Repair "Passing arbitrary data..." broken link

src/bindgen.rs
In debug mode `wasm-bindgen` emits more JS glue to check more invariants
and otherwise provide more sanity checks. This is omitted by default
with wasm-pack as it runs in release mode by default, but if `--debug`
is passed let's be sure to include it!
=> Pass `--debug` to `wasm-bindgen` in debug mode

CONTRIBUTING.md
closes #352 
Added a section to the `CONTRIBUTING.md` file that covers adding IDE configuration files to a global .gitignore. Any feedback on better wording, formatting, etc is much appreciated! 😄 
---
```bash
```
=> Add section on IDE config files to CONTRIBUTING.md

Cargo.lock, README.md, src/build.rs, src/command/build.rs, src/emoji.rs, src/error.rs
fixes https://github.com/rustwasm/wasm-pack/issues/351
=> feat(build): add rustc check

CHANGELOG.md
some minor fixes for copy-pastability of the cli flags!
(the `broswer` typo is also in https://github.com/rustwasm/wasm-pack/releases, while the `--target`s are already fixed)
=> fix(changelog): fix some typos

src/test/mod.rs, tests/all/utils/fixture.rs
These look to have been removed elsewhere, so seem to be left in by
mistake!
=> Remove lingering forced nightly usages

src/bindgen.rs, src/build.rs, src/child.rs, src/command/build.rs, src/command/login.rs, src/command/mod.rs, src/command/pack.rs, src/command/publish/mod.rs, src/command/test.rs, src/error.rs, src/lib.rs, src/manifest/mod.rs, src/npm.rs, src/test/mod.rs, src/test/webdriver.rs, tests/all/main.rs, tests/all/utils/fixture.rs, tests/all/utils/logger.rs, tests/all/utils/mod.rs
Fix #287 but also all the instances of this that we might ever run into.
=> Child process and output management

src/binaries.rs, src/bindgen.rs, src/build.rs, src/child.rs, src/command/build.rs, src/command/login.rs, src/command/mod.rs, src/command/pack.rs, src/command/publish/mod.rs, src/command/test.rs, src/command/utils.rs, src/error.rs, src/installer.rs, src/lib.rs, src/lockfile.rs, src/logger.rs, src/manifest/mod.rs, src/npm.rs, src/readme.rs, src/test/mod.rs, src/test/webdriver.rs, tests/all/main.rs, tests/all/utils/fixture.rs, tests/all/utils/logger.rs, tests/all/utils/mod.rs
:zap: Do not merge this at this point. :zap:
This PR intends to fix #280. This PR is branched out from @fitzgen branch in #392.
=> Return `Result<T, failure::Error>` instead of `Result<T, wasm_pack::error::Error>`

tests/all/readme.rs
I found this while working on #411, just a small typo in the test file for copying the README. I figured it would be better to make a separate PR for this instead of including it in 411 since it was unrelated to the rest of the implementation of that feature.
```bash
```
=> Fix typo in test function name for copying the README

.appveyor.yml, Cargo.lock, src/command/build.rs, src/error.rs, tests/all/bindgen.rs, tests/all/manifest.rs
=> Add no-modules to --target flag's help text

.travis.yml
=> CI: Use `name` field for Travis CI jobs

tests/all/build.rs
=> Build crate in a workspace

src/bindgen.rs, src/command/build.rs, src/command/test.rs, src/lockfile.rs, src/manifest/mod.rs, tests/all/build.rs, tests/all/lockfile.rs, tests/all/manifest.rs, tests/all/test.rs, tests/all/utils/fixture.rs
This commit fixes an issue where if a library is renamed via the `name`
key in the `[lib]` section of the manifest then `wasm-pack` would try to
generate bindings for an noexistent wasm-file, generating an error.
The fix was to internally use `cargo_metadata` more aggressively and
move around where this data is generated. This ended up refactoring a
few locations, but this should also bring improved error messages for
`cargo metadata` as well as caching the resulting data more aggressively
to avoid recalculating it too much.
Closes #339
=> Fix wasm-bindgen if lib is renamed via `lib.name`

src/command/test.rs, tests/all/test.rs
The `cdylib` crate type output isn't actually necessary for the
`wasm-pack test` stage because `wasm-bindgen` isn't run over a wasm
file. This commit removes the checks during `wasm-pack test` that the
`cdylib` crate type is configured.
=> Don't require cdylib crate-type for testing

src/command/utils.rs, tests/all/build.rs, tests/all/utils/fixture.rs
This PR addresses problems with canonical paths on windows that were reported in #380. I tested this by building a wasm app with a few dependencies on windows.
I would love somebody to check the work and try running it on another windows box targeting another wasm app 😄 .
Implementation:
Remove the usage of std::fs::canonicalize.
Unit test:
I added a unit test based on reported failures:
- a project with local transitive dependencies, see #413
=> fix canonical paths windows

Cargo.lock, Cargo.toml
Updating to the latest version of the `zip` crate. This version also brings a bunch of performance improvements which might come in handy.
=> update zip to 0.5.0

Cargo.lock, Cargo.toml, src/command/build.rs, src/lib.rs, src/license.rs, src/manifest/mod.rs, tests/all/license.rs, tests/all/main.rs, tests/all/utils/fixture.rs
Closes #407 
Added a new step to `build` that will look in the Cargo.toml file to see if a license key has been set. If one has been set it will glob for `LICENSE*` and copy those file(s) to the specified `out` directory. If a license key has not been set this step will skip with the message `No LICENSE found in Cargo.toml skipping...`. If a key is set in the Cargo.toml but the glob doesn't match any files we will break out of the copying license step and print `License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory` to the console.
I would love some feed back on the file globing implementation. I am pretty new to Rust but as far as I can tell the best way to account for the different ways `LICENSE` files can be named …
=> Copy license file(s) to out directory

Cargo.lock, Cargo.toml, src/lib.rs, src/manifest/mod.rs, tests/all/manifest.rs
=> feat: Catch typos in Cargo.toml and warn about them

src/command/utils.rs
As per discussion with @ashleygwilliams in https://twitter.com/ag_dubs/status/1068173944807727110, `pkg` should be commonly ignored, and the simplest way to do that is to just generate nested `.gitignore` inside it ignoring everything (including `.gitignore` itself).
---
```bash
```
=> Generate self-.gitignore as part of pkg folder

.github/PULL_REQUEST_TEMPLATE.md, rust-toolchain
This allows new contributors to avoid manually running `rustup override set nightly`.
=> Add rust-toolchain file set to nightly

src/license.rs
Closes #475 
I've changed the code that utilized `unwrap()`and handled the `None` case of the option explicitly returning an Error if we get a `None`.
Side note: I also refactored a couple of places in the file based on some clippy linting warnings.
---
```bash
```
=> Refactor license copy to remove unwrap()

src/npm.rs
1. Fixes Issue #486: Empty input prompt when `login`.
2. Fixes `login` arguments being accidentally merged together when spawning `npm adduser`.
See the text of each commit for more details.
- [✅] You ran `cargo fmt` on the code base before submitting
- [✅] You reference which issue is being closed in the PR text
=> Login issues

src/command/build.rs
=> validate target argument

docs/src/tutorial/template-deep-dive/cargo-toml.md, docs/src/tutorial/template-deep-dive/src-lib-rs.md, docs/src/tutorial/template-deep-dive/src-utils-rs.md
Closes issues #345, #346 by adding deep dives for `src/lib.rs` and `src/utils.rs`. Also updates original deep dive text to latest template.
Tested using `mdbook build`.
- [✅] You ran `cargo fmt` on the code base before submitting
- [✅] You reference which issue is being closed in the PR text
=> Complete template deep dives

src/child.rs, src/npm.rs
Issue #277 - Affects running login, pack, and publish on Windows.
Wraps `Command::new` by `child::new_command(program: &str)`. This prepends `cmd /c` to the program name if `cfg!(windows)`. See rustc: #42436, #42791, #44542
See commits for more details. Tested build/login/pack/publish on the latest stable Windows, Mac, and Ubuntu.
- [✅] You ran `cargo fmt` on the code base before submitting
- [✅] You reference which issue is being closed in the PR text
=> Windows fixes

Cargo.lock, Cargo.toml, src/cache.rs, src/command/build.rs, src/command/test.rs, src/lib.rs, src/progressbar.rs, src/test/mod.rs, tests/all/main.rs, tests/all/test.rs, tests/all/utils/fixture.rs
Also introduces testing of our CLI's output via `assert_cmd`. Expect some follow ups to get more of our testing infrastructure using this incredible crate!
Fixes #511
=> Only print `cargo test` output the once

src/license.rs, src/manifest/mod.rs, tests/all/license.rs, tests/all/utils/fixture.rs
```bash
```
- I checked issues list. No issue was found.
In my package, no `license` field is provided in `Cargo.toml`, but `license-file` is provided. I noticed `wasm-pack` does not copy license file specified in `license-file` field.
https://doc.rust-lang.org/cargo/reference/manifest.html
This patch supports `license-file` field by following two additions:
- `wasm-pack` copies file specified in `license-file` in `Cargo.toml` into `pkg` directory
- Set `"SEE LICENSE IN <filename>"` to `license` field of `package.json`. This is standard way documented in official npm document: https://docs.npmjs.com/files/package.json#license
I added one new test case to check my implementation works fine.
> …
=> Support license-file field in Cargo.toml

src/manifest/mod.rs, src/manifest/npm/commonjs.rs, src/manifest/npm/esmodules.rs, src/manifest/npm/nomodules.rs, tests/all/manifest.rs, tests/all/utils/manifest.rs
```bash
```
- I searched 'homepage' word but no open issue was found
Both `Cargo.toml` and `package.json` have `homepage` field. They are meaning the same so I thought `homepage` field should be copied from `Cargo.toml` into `package.json`. This patch implements the feature.
- Cargo.toml
- https://doc.rust-lang.org/cargo/reference/manifest.html
- package.json
- https://docs.npmjs.com/files/package.json#homepage
=> Support 'homepage' field of Cargo.toml and package.json

docs/src/commands/build.md, docs/src/commands/test.md, src/build.rs, src/command/build.rs, src/command/test.rs, src/test/mod.rs
=> Pass arguments through to cargo test

src/command/build.rs, src/manifest/mod.rs, tests/all/manifest.rs
```bash
```
Currently, `wasm-pack` copies `README.md` and license files into `pkg` directory. But they are not listed in `files` field of `package.json`. `npm publish` does not contain the copied files. This causes 2 problems:
- README.md is not reflected in npmjs.com's package page
- User cannot look the copyright notice of the license file in installed package directory in `node_modules`. Some famous license (e.g. MIT) requires to show copyright notice. So it's better to contain license file in the installed package directory.
Add `README.md` and detected license files to `files` field of generated `package.json`.
e.g.
```
{
"name": "foo",
// ...
"files": [
"foo_bg.wasm",
"foo.js", …
```
=> Add license files and README file to 'files' field of package.json

src/manifest/mod.rs, tests/all/build.rs, tests/all/manifest.rs, tests/all/test.rs, tests/all/utils/fixture.rs
=> rebase + cargo fmt Fitzgen use assert cmd everywhere

src/test/webdriver.rs, tests/all/webdriver.rs
This solves #535.
Changes:
* use win32 chromedriver binary on win64 systems
* update chromedriver version to 2.45
* fix error message
=> Use win32 chromedriver binary on win64, update chromedriver version and fix error message

src/command/mod.rs
Was confused for a sec when I saw this in `--help`.
=> Clarify what kind of account `login` adds

docs/src/SUMMARY.md, docs/src/tutorial/template-deep-dive/src-lib-rs.md, docs/src/tutorial/template-deep-dive/wee_alloc.md
(I didn’t check any of the boxes 😭)
I created a section about `wee_alloc` in the template deep-dive to make `wee_alloc` stand out a bit more. 
I also added some more explicit explanation on how to enable it. I tried to match the tone, hope I succeeded :)
Let me know if this works for ya :)
=> [Docs] Add wee_alloc section

clippy.toml, src/child.rs, src/command/build.rs, src/command/login.rs, src/command/mod.rs, src/command/publish/mod.rs, src/command/utils.rs, src/installer.rs, src/lockfile.rs, src/manifest/mod.rs, src/npm.rs, src/progressbar.rs, src/readme.rs
closes #477 
This is a first pass PR at cleaning up the clippy warnings. Most of them were simple enough refactors that it only took minor modifications to the code to get rid of the warnings. There were a few warnings, marked by `#![allow()]`, that would require more significant changes to the code structure so instead of going ahead and implementing those changes I marked them as clippy allow until we can decide if the changes are something we want or not.  
---
```bash
```
=> Refactor: fix clippy warnings

.travis.yml
When #478 gets merged I think we should run `clippy` at Travis.
=> chore(travis): Run clippy check

src/bindgen.rs, src/build.rs, src/command/test.rs
And therefore should not be all caps.
https://webassembly.github.io/spec/core/intro/introduction.html#wasm
v important
=> "Wasm" is a contraction, not an acronym

src/manifest/mod.rs, tests/all/license.rs, tests/all/manifest.rs, tests/all/utils/fixture.rs
=> fix(manifest): LICENSE and README don't need to be whitelisted

src/main.rs
🔕 do no merge 🔕 
fixes #518 
@alexcrichton how should we test this? (if at all?) are there security implications for not doing the exact match that i'm not thinking of?
=> fix(exe): wasm-pack-init (1).exe should work

.appveyor.yml, .travis.yml, binary-install/Cargo.toml, binary-install/src/lib.rs, binary-install/tests/all/cache.rs, binary-install/tests/all/download.rs, binary-install/tests/all/main.rs, binary-install/tests/all/utils/mod.rs
This PR will add some tests to the binary install crate. Please review even that it's WIP. I appreciate any comments what so ever.
=> test(binaryinstall): Add initial tests

.travis.yml, docs/_theme/header.hbs
This commit adds a header dialog to the gh-pages mdbook documentation of
this repository to indicate that it represents unpublished documentation
that may not reflect the currently published version of `wasm-pack`. The
header redirects users to https://rustwasm.github.io/docs/wasm-pack/
which has the documentation for the latest published version of
`wasm-pack`.
=> Flag gh-pages docs as unpublished

docs/src/commands/build.md, src/bindgen.rs, src/command/build.rs, src/command/publish/mod.rs, src/manifest/mod.rs, tests/all/manifest.rs
This commit adds support for the new `--web` flag in `wasm-bindgen`
under the flag name `--target web`. To ensure that it was plubmed around
the stringly-typed `target` type was switched to an `enum Target` to
ensure that all cases it's looked at are handled appropriately for the
new `web` target.
=> Add support for `--target web`

docs/src/commands/build.md
=> doc(build): add entry for --out-dir

src/command/build.rs, tests/all/build.rs
This commit fixes the `wasm-pack build --mode no-install` command from
unconditionally panicking as well as `--mode force`. These steps were
calling an `unwrap()` on an internal `Option<T>` which was supposed to
be set during `step_install_wasm_bindgen`, but that step wasn't run in
these modes. The mode configuration of steps has been refactored
slightly to ensure that more steps are shared between these modes to
reduce duplication.
=> Fix panics in `build --mode no-install`

docs/src/commands/build.md
I checked the boxes in case there's a bot checking for them, but this doesn't involve any actual lines of code, just replacing "Th" with "This" in a single place in a doc page.
I'd make an issue and everything, I do actually like following procedure...but it seems like overkill.
Thanks for your time!
```bash
```
=> Fixed a single typo

src/main.rs
This will print to standard error for unexpected panics and then let `human_panic` handle panics, just like before.
This will fix #562.
=> feat: Print unexpected panics to standard error

docs/src/commands/build.md, src/bindgen.rs, src/command/build.rs, src/command/test.rs, src/manifest/mod.rs, tests/all/license.rs, tests/all/lockfile.rs, tests/all/manifest.rs
Closes #596 
Should I also add tests for this feature?
=> Added support for --out-name flag

src/build/wasm_target.rs
When checking for wasm32 target we did check if the sysroot contained ".rustup". While this covered the most common cases it didn't work when using Docker. So checking for "rustup" instead covers both
cases.
I also noticed another bug where if the target was found we printed the helpful information and not the way around so I fixed that as well. Also, the code linked to the wrong docs section since the last docs update so I corrected that.
This will fix #613
=> fix: Check for "rustup" rather than ".rustup" when checking for wasm32

src/build/mod.rs, src/command/build.rs, src/main.rs, src/manifest/mod.rs
As mentioned in #409, some comments mentioned to use `?` over calling `.unwrap()` and to use a struct instead of two Strings. This PR leverages `?` and a new struct called `WasmPackVersion` with a `local` and `latest` field. This PR also uses `PBAR.warn(warning_msg)` instead of `println!(warning_msg)`
to print the warning message. I also changed `which::which("wasm-pack")` to `env::current_exe()`.
=> refactor: Use PBAR.warn and a struct for versions

RELEASE_CHECKLIST.md
=> doc(release): add release checklist

docs/src/commands/test.md, src/command/test.rs
This builds on rustwasm/wasm-bindgen#1465 by ensuring that `wasm-pack
test --node` will now only test node.js tests
=> Only run specific tests during `wasm-pack test`

README.md
The docs have changed a bit and this link no longer exists, so let's remove it.
=> doc(readme): Remove obsolete link

src/manifest/mod.rs
This PR adds a user agent header for the wasm-pack version check. It will look like this: `User-Agent: wasm-pack/0.8.1 (https://github.com/rustwasm/wasm-pack)`.
Fixes #651.
=> fix: Add user agent for wasm-pack version check

.github/PULL_REQUEST_TEMPLATE.md
```bash
```
---
Fixes #639. Updates `rustfmt` install instructions in PR template :smile_cat:
=> update rustfmt install snippet in pull request template

README.md
Fix broken url , update generate command name to "new"
```bash
```
=> Update README.md: fix broken url, update "generate"command name to "new"

Cargo.lock, Cargo.toml, src/manifest/mod.rs
```bash
```
This updates `cargo_metadata` to 0.8.0. The semantics slightly changed, but other than that there's not a lot of difference. The error type is simplified, which means a conversion function is no longer needed.
I was hoping this would fix (it doesn't) #637, but unfortunately not.
=> Update cargo_metadata to 0.8.0

src/command/build.rs, src/command/mod.rs, src/command/pack.rs, src/command/publish/mod.rs, src/command/test.rs, src/command/utils.rs, tests/all/build.rs, tests/all/manifest.rs
PR for #620 Walk up parent directories to find the current crate
When setting the crate path, if the default path of the current working directory is defined pass back a flag indicating the default was used
If the default is used, and a path is not specified, then walk up the path to find the Cargo.toml file
I'm relatively new to Rust and figured this was a good first step to getting to know the project and wet my feet, but I'm not sure I'm doing things the idiomatic way - so I'm happy to have all and any feedback!
=> Recurse up the path looking for the Cargo.toml

tests/all/build.rs
`wasm-bindgen` regressed and only generates move assertions for free functions,
not methods. While `wasm-bindgen` is fixing that regression, we are changing
this test fixture to be of the shape that will still generate move assertions.
Fixes #677.
=> test: Ensure that `wasm-bindgen` will generate move assertions

Cargo.lock, Cargo.toml, src/bindgen.rs, src/child.rs, src/install/mod.rs, src/lib.rs, src/manifest/mod.rs, tests/all/build.rs
#633 with merge, edits, and test
=> check wasm-bindgen version if running with target web

src/bindgen.rs, src/command/build.rs, tests/all/utils/fixture.rs
fixes #681 #597 
no breaking changes in this but preps to make breaking changes in 0.10.0 per #686
=> feat(bindgen): update to --target flag interface

docs/src/commands/pack-and-publish.md, src/command/mod.rs, src/command/publish/mod.rs, src/npm.rs
I haven't created a ticket and couldn't find any. I hope it is still ok to submit this small PR, which fits my needs.
This PR adds a new option to `wasm-pack publish` for publishing tagged releases.
See [dist-tags](https://docs.npmjs.com/cli/dist-tag) on NPM for further explanation of distribution tags.
=> feat(publish): dist tag option

Cargo.lock, Cargo.toml, RELEASE_CHECKLIST.md, src/lib.rs, src/stamps.rs, src/test/webdriver.rs, src/test/webdriver/chromedriver.rs, src/test/webdriver/geckodriver.rs, src/test/webdriver/safaridriver.rs, tests/all/main.rs, tests/all/stamps.rs
Closes #611
**Changes**
- `webdriver.rs` split into `chromedriver.rs`, `geckodriver.rs` and `safaridriver.rs` for better code organization.
- Functions `install_geckodriver` and `install_chromedriver` fetches info about the latest `*driver` version so they can find out if we are using the latest `*driver`.
**Testing**
- I've tested it locally on Windows 10 - it downloads both drivers without problems.
- There are new / updated `curl` calls - should I test it in unit/integration tests somehow? (Is there an example for inspiration?)
**Possible future improvements**
- We can fetch info about a new `[chrome/gecko]driver` only when testing fails because of old driver and then restart testing.
- **+** A little bit faster testing.
- **+** We probably don't need internet connection during …
=> Select correct webdriver version

src/build/mod.rs, src/main.rs, src/manifest/mod.rs, src/stamps.rs
This PR will fix #652 and #653.
=> fix: Rate limit version check if the request fails and output warning if version check fails

npm/.gitignore, npm/README.md, npm/binary.js, npm/package-lock.json, npm/package.json, npm/run.js
This PR creates an npm installer for `wasm-pack` that downloads and installs a binary. It uses this unpublished package for installing binaries https://github.com/everlastingbugstopper/binary-install. 
It currently downloads from a workers.cloudflare endpoint that we'd likely want to change to something that the rustwasm working group has control over.
We also probably want some more keywords before this would be published - currently I've just copied the same tags from the repository.
Proof that it works
```console
$ cd ./wasm-pack/npm
$ npm i -g
> wasm-pack@0.8.1 postinstall 
> node -e 'require("./binary.js").install()'
Downloading release https://workers.cloudflare.com/get-binary/rustwasm/wasm-pack/v0.8.1/x86_64-apple-darwin.tar.gz
wasm-pack has been installed!
+ wasm-pack@0.8.1 …
```
=> Create npm installer

npm/install.js, npm/package-lock.json, npm/package.json, npm/run.js, npm/uninstall.js
Fixes #757 
Not sure how we'll actually release this given that our npm installer version number is tied to the version of wasm-pack. Might need to do a point release of wasm-pack that does nothing? Alternatively we can do a release of everything that's been merged to master since April, not sure if that's the direction we want to go though.
cc @ashleygwilliams
=> Bump binary-install version to fix Windows installs

docs/src/commands/index.md, docs/src/commands/new.md
=> fix(docs): fix broken link and typo for "Commands"

docs/src/cargo-toml-configuration.md, src/command/build.rs
In light of our [upcoming release](#760) and the [reported bug](https://github.com/rustwasm/wasm-pack/issues/696) regarding `wasm-opt` on Linux, this PR updates the docs and includes a helpful error message on failed `wasm-opt` executions.
Output looks like this:
```console
$ wasm-pack build --release
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
Finished release [optimized] target(s) in 0.02s
[INFO]: Optimizing wasm binaries with `wasm-opt`...
Error: failed to execute `wasm-opt`: exited with exit code: 1
full command: "/Users/averyharnish/Library/Caches/.wasm-pack/wasm-opt-86de3fed0e357d00/wasm-opt" "/Users/averyharnish/Documents/work/_tmp/test-wasm/pkg/test_wasm_bg.wasm" "-X" "/Users/averyharnish/Documents/work/_tmp/test-wasm/pkg/test_wasm_bg.wasm-opt.wasm" …
```
=> Add docs and actionable error message for failed wasm-opt executions

tests/all/build.rs
This PR adds an end to end integration test that assures that a user can run successfully run the following commands:
```console
$ wasm-pack new my-project
$ cd my-project
$ wasm-pack build
```
=> Adds end to end test for building a generated project

docs/_installer/index.html
=> doc: Document installation via npm or yarn

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/index.html, npm/package-lock.json, npm/package.json
Reverts rustwasm/wasm-pack#785
getting a local test failure on installing browser drivers. CI doesn't appear to catch it but have confirmed it on MacOS and windows.
=> Revert "0.9.1"

src/manifest/mod.rs, src/manifest/npm/commonjs.rs, src/manifest/npm/esmodules.rs, src/manifest/npm/nomodules.rs, tests/all/manifest.rs, tests/all/utils/manifest.rs
```bash
```
Closes #707 
package.json files usually contain a `keywords` array so that npm can make searching easier. Currently the keywords from the Cargo.toml are not exported to the package.json, meaning they have to be done manually before a package is published to npm, or be difficult to find on npm.
This is my first edit, so please let me know if I have made some junior mistakes
=> Added keywords (#707)

src/manifest/mod.rs, tests/all/manifest.rs
```bash
```
Closes #837
`wasm-pack build` and `wasm-pack build --target bundler` generate a _bg.js file, but it is not added to the package.json. The file that is added, *.js will however reference the _bg.js, so when the package is distributed (both through `pack` or `publish`) it is not usable.
This change will fix that by passing the correct bool value to npm_data
As is the same for my other PR, there is some test failure that I locally also have on the master branch. Please let me know how to address this if possible
=> Corrected files included in package.json for bundler / no target (#837)

README.md
This is a very small change to the README, not an actual issue (not a bug or feature request) so I am not sure about how to handle it. In the [contributing guidelines](https://github.com/rustwasm/wasm-pack/blob/master/CONTRIBUTING.md) I could not find instructions. Maybe it would be a good addition (under docs category)?
Anyway, while checking the repository, I noticed you reference greenkeeper in the README, but it is going to be taken down in less than a month, so I think it is better to avoid stale links.
=> docs: Remove greenkeeper reference from readme, as it is being retired

src/progressbar.rs, tests/all/log_level.rs, tests/all/manifest.rs
=> Fix logs for uniformity (#716)

src/install/mod.rs
=> Fix cargo-generate installation

npm/binary.js, npm/package-lock.json, npm/package.json
Closes #958. Co-PR to #973.
Based on https://github.com/rustwasm/wasm-pack/pull/973#pullrequestreview-589981499, I've ran `node run.js` and verified that this works.
If we'd like, I'm down to add a test subcrate that's runs `node run.js build` to actually run the full build. Thoughts?
```bash
```
=> Binary install update for axios security vulnerability.

npm/package-lock.json, npm/package.json
```bash
```
This PR fixes #958.
=> Fix #958: Update binary-install in package.json to fix security alert

docs/src/tutorials/npm-browser-packages/template-deep-dive/wee_alloc.md
That section is gone.
```bash
```
=> cleanup: remove outdated TOC heading

docs/src/tutorials/npm-browser-packages/template-deep-dive/wee_alloc.md
=> fix(docs): remove duplicated "is" in the wee_alloc tutorial

docs/src/introduction.md
Greenkeeper said goodbye in June 2020, so no longer good to link to as an example.
Alternative might be to link to Snyk instead?
Issue #1001 
```bash
```
=> remove greenkeeper

.github/workflows/approve.yml
Using https://github.com/marketplace/actions/automatic-approve solves the problem of approval of new PRs for Github action running (providing they don't edit the workflows themselves!)
---
```bash
```
=> Automatically approve new PRs for running Github test actions

.github/workflows/book.yml
All 1.x versions of [ammonia](https://crates.io/crates/ammonia/versions) have been yanked, so mdbook 0.2 isn't installable anymore. This PR upgrades to 0.3, and runs the build part of mdbook on PRs so we can pick up issues like this before master merge.
---
```bash
```
=> Fix mdbook build

src/command/build.rs, tests/all/build.rs
The syntax for passing extra arguments to `wasm-pack build` and `wasm-pack test` has diverged due to #851, with the result that an additional `--` is expected by `wasm-pack build` but not by `wasm-pack test`:
```
wasm-pack build -- --features foo
wasm-pack test --features foo
```
This PR mirrors the change made in #851 and applies it to `wasm-pack build` so that both commands use the same syntax again (without the need for an extra `--` and with the same syntax as `cargo build` and `cargo test`):
```
wasm-pack build --features foo
wasm-pack test --features foo
```
---
```bash
```
=> Use same syntax for extra arguments as wasm-pack test

docs/src/commands/build.md, docs/src/commands/test.md, docs/src/tutorials/npm-browser-packages/template-deep-dive/wee_alloc.md
Since #851 was merged, both `wasm-pack build` and `wasm-pack test` directly pass extra arguments to `cargo build` and `cargo test` without the need for an additional `--`. This PR updates the docs to reflect this change.
EDIT: I just noticed that `wasm-pack build` did not yet use the same syntax as `wasm-pack test`, which would be fixed by #1037 and should be merged first for the doc changes of this PR to make sense.
---
```bash
```
=> Fix example commands in docs broken by PR #851

docs/src/SUMMARY.md, docs/src/prerequisites/considerations.md
- [✅ ] You have the latest version of `rustfmt` installed
```bash
```
- [✅ ] You ran `cargo fmt` on the code base before submitting
- [✅ ] You reference which issue is being closed in the PR text #1033 
=> feat(docs): Prerequisites, considerations for nodejs #1033

docs/_theme/header.hbs
I just put the warning header in a `p` tag so that it wouldn't render offscreen.
There's some extra whitespace in the bottom margin of the warning header but I thought I'd keep the change atomic.
- [ ✅] You have the latest version of `rustfmt` installed
```bash
```
- [ ✅] You ran `cargo fmt` on the code base before submitting
- [ ✅] You reference which issue is being closed in the PR text
=> fixes docs offscreen warning label 

src/wasm_opt.rs
First look in the local path for the wasm-opt binary. Use whatever binary is found and assume it works.
I'm specifically working on an ARM Mac and was able to build wasm-opt locally but wasm-pack wasn't picking it up. I found that the code used to support this so I copied it back https://github.com/rustwasm/wasm-pack/commit/9b74e43d2de3c0c1eccdc3752c870925b68fb27a#diff-d9cd988699c3224bc78800edb64a7cb60d3cae9833460f79ce2d586b9555cd83R70
Referenced in this issue https://github.com/rustwasm/wasm-pack/issues/913
I'm kinda new at this so I'm willing to accept whatever guidance is necessary for this. Thanks for creating this project!
```bash
```
- [✅] You ran `cargo fmt` …
=> Re-enable looking in the path Wasm-opt for binaries first.

Cargo.lock, Cargo.toml, tests/all/main.rs
`serial_test` since [0.3](https://github.com/palfrey/serial_test/releases/tag/v0.3.0) includes `serial_test_derive` and lets you use the macro without needing to directly include `serial_test_derive`
=> Remove direct usage of serial_test_derive

src/bindgen.rs, src/build/wasm_target.rs, src/command/build.rs, src/emoji.rs, src/install/mod.rs, src/installer.rs, src/manifest/mod.rs, src/test/webdriver.rs
While struggling with an issue I reviewed some of wasm-pack's source to understand how it works better. En route, I found minor details I wound up poking at: borrows that are re-borrowed and clones that could be skipped, mostly.
=> fix: todo, minor typos, extra clones

docs/src/tutorials/npm-browser-packages/template-deep-dive/src-lib-rs.md
I guess this would be correct...
Thank you for this great tool.
```bash
```
=> Fix duplication of lines in docs

npm/binary.js, npm/package-lock.json
=> fix: Add exe to binary name if windows

.github/workflows/release.yml
Build and release `aarch64-unknown-linux-musl` target. Solves first part of https://github.com/rustwasm/wasm-pack/issues/1064.
With this change we can easily add more targets in the future. Once GH updates `macos-latest` to using MacOS 11, we can add `aarch64-apple-darwin`.
You can see that the release workflow succeeds here: https://github.com/nacardin/wasm-pack/actions/runs/1291954371
- [ x ] You have the latest version of `rustfmt` installed
- [ x ] You ran `cargo fmt` on the code base before submitting
- [ x ] You reference which issue is being closed in the PR text
=> Add linux/arm64 to release workflow

npm/binary.js, src/install/mod.rs, src/target.rs
This PR fixes #913 for MacOS (aarch64) and will download `x86_64-apple-darwin`. Ideally, binaryen would release a native build but until then we can just use the x86 version which works fine on Apple Sillicon.
```bash
```
=> feat: add support for macos aarch64

docs/src/commands/build.md
This is the correct way to pass extra arguments, such as features to cargo.
This fixes #1059.
```bash
```
=> Update docs for how to pass extra options to cargo.

src/command/utils.rs
A recent commit (d79e72189c523586debcee2ebbf6a2fd065e8abf) ensured that the `pkg` directory was removed as the first step of attempting to create it. Unfortunately, this causes a problem for [webpack](https://webpack.js.org/) when watching the `pkg` directory. Webpack is unable to recover its watching and so any watch server must be restarted, which is a blocker when using it.
Please note that there was [some debate](https://github.com/rustwasm/wasm-pack/pull/986#discussion_r676967231) about whether to remove the `pkg` directory. It is unclear to me what the actual benefits of it are, and whether this PR re-introduces some other problem. However, wasmpack appears to have existed as per the behaviour of this PR for a few years.
This PR reverses the change made in the above commit and fixes …
=> Do not remove the pkg directory

src/command/utils.rs
Remove the package.json file from previous runs to avoid crashes, as discussed in https://github.com/rustwasm/wasm-pack/pull/1110#issuecomment-1059008962
=> Clean up package.json from previous runs

.github/workflows/release.yml
This PR fixes #1097 by using `bash` to create the tarball on Windows.
The issue was probably caused by the behaviour of the `|` operator with the default shell (PowerShell on Windows runners I believe).
=> Use `bash` to create release tarballs

src/install/mod.rs
Bump `wasm-opt` to version 108. Solves performance issues caused by the outdated version ()
Closes #1135. 
```bash
```
=> Bump `wasm-opt` to version 108.

npm/binary.js, npm/package.json, npm/run.js, npm/uninstall.js, npm/yarn.lock
also removes `run.js` and `uninstall.js` as they are not needed
=> chore: updates binary-install to v1.0.1

src/bindgen.rs, src/command/build.rs, src/manifest/mod.rs
```bash
```
This PR makes Deno available since `wasm-bindgen` does support it as a target now.
This PR continues the work done in https://github.com/rustwasm/wasm-pack/pull/908. I decided to push the discussed changes here as a separate PR as the original PR creator did not seem to be working on this anymore.
Related PR
https://github.com/rustwasm/wasm-pack/pull/908
Related issues
https://github.com/rustwasm/wasm-pack/issues/672
https://github.com/rustwasm/wasm-pack/issues/879
=> Make Deno target available

docs/_installer/init.sh
This makes the installation script work on M1 macs, as well as inside docker (especially when combined with buildx) for aarch64/arm64 architectures.
Related:
- https://github.com/rustwasm/wasm-pack/issues/1064
- https://github.com/rustwasm/wasm-pack/issues/952
- https://github.com/rustwasm/wasm-pack/issues/1125
=> Add suppot for more platforms to installer script

npm/binary.js
Adds support for Linux arm64 in the wasm-pack npm package.
Fixes: #1169 
```bash
```
=> Add Linux arm64 support

src/bindgen.rs, src/command/build.rs
Fixes #930 
Closes #888 
I'm wondering if it'd make sense to have a --bind-gen-opts flag which allows the user to manually specify args to pass through
=> Pass through --weak-refs --reference-types flags to bindgen

Cargo.lock, Cargo.toml, src/manifest/mod.rs, tests/all/log_level.rs, tests/all/manifest.rs
This PR adds support for reading metadata from crates using the [workspace inheritance](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table) feature introduced in [Rust 1.64](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds).
I've implemented this by bumping the `cargo_metadata` dependency to the latest version, and using its metadata for the `description`, `license`, `license-file`, `repository` and `homepage` fields, instead of parsing the `Cargo.toml` file directly. This should also make `wasm-pack` more resilient to future `Cargo.toml` format changes.
I've tested the change locally and it seems to work perfectly.
Fixes #1180.
---
```bash
$ rustup …
```
=> Add support for workspace inheritance

docs/src/commands/build.md, docs/src/contributing.md
This PR just includes a couple small fixes (typos/grammar/etc) that I noticed as I was reading the wasm-pack docs
=> Docs fixes

docs/src/commands/build.md, docs/src/tutorials/npm-browser-packages/packaging-and-publishing.md
Two small documentation fixes.
=> Replace two mentions of `wasm-pack init` with `wasm-pack build` in the docs

npm/package.json
hopefully we can get this in before the release happens otherwise i fear the npm installer may break! i meant to open this PR sooner but just never got around to it. [this](https://github.com/apollographql/rover/pull/1108) is the patch i submitted to the primary repo I work on for comparison to this PR. 
We ended up burning [two](https://github.com/apollographql/rover/releases/tag/v0.5.2) [releases](https://github.com/apollographql/rover/releases/tag/v0.5.3) due to npm install woes, but things are working smoothly now. cc @drager
=> fix: adds back run.js to npm installer

docs/src/prerequisites/npm.md
https://www.npmjs.com/get-npm doesn't immediately explain how to install npm anymore which can lead to some [confusion](https://www.reddit.com/r/rust/comments/10z5xyp/do_i_have_to_set_up_an_npm_account_to_do_rust_wasm/). https://docs.npmjs.com/downloading-and-installing-node-js-and-npm seems like the best page to link to instead.
=> Docs: Update npm installation link

src/manifest/mod.rs, src/manifest/npm/esmodules.rs, tests/all/manifest.rs, tests/all/utils/manifest.rs
This is a less extreme version of #1208, which only marks snippets and the main file on the bundler target as having side effects instead of all files.
This means that the JS shim file which contains the vast majority of the JS code is still properly marked as having no side effects, allowing bundlers to get rid of things like unused `new TextEncoder` calls which could theoretically have side effects but don't.
Fixes #972
Fixes rustwasm/wasm-bindgen#3276
=> Mark snippets and the bundler target's main file as having side effects

.github/workflows/book.yml, .github/workflows/release.yml, .github/workflows/test.yml
Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest major version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.3.0
> - Implement branch list using callbacks from exec function
> - Add in explicit reference to private checkout options
> - Fix comment typos
>
> ## v3.2.0
> - Add GitHub Action to perform release
> - Fix status badge
> - Replace datadog/squid with ubuntu/squid Docker image
> - Wrap pipeline commands for submoduleForeach in quotes
> - Update @actions/io to 1.1.2
> - Upgrading version to 3.2.0
>
> ## v3.1.0
> - Use @actions/core `saveState` and `getState`
> - Add `github-server-url` input
>
> ## v3.0.2
> - Add input `set-safe-directory`
>
> ## v3.0.1
> - Fixed an issue where checkout failed to run in container …
=> Update actions/checkout in GitHub Actions workflows to v3

.github/workflows/book.yml, .github/workflows/test.yml
Updates the `actions/cache` action used in the GitHub Actions workflow to its newest major version.
Changes in [actions/cache](https://github.com/actions/cache):
> ### 3.0.0
> - Updated minimum runner version support from node 12 -> node 16
> 
> ### 3.0.1
> - Added support for caching from GHES 3.5.
> - Fixed download issue for files > 2GB during restore.
> 
> ### 3.0.2
> - Added support for dynamic cache size cap on GHES.
> 
> ### 3.0.3
> - Fixed avoiding empty cache save when no files are available for caching. ([issue](https://github.com/actions/cache/issues/624))
> 
> ### 3.0.4
> - Fixed tar creation error while trying to create tar with path as `~/` home folder on `ubuntu-latest`. ([issue](https://github.com/actions/cache/issues/689))
> 
> ### 3.0.5
> - Removed error handling by …
=> Update actions/cache in GitHub Actions workflows to v3

.github/workflows/book.yml
Updates the [`JamesIves/github-pages-deploy-action`](https://github.com/JamesIves/github-pages-deploy-action) action used in the GitHub Actions workflow to its newest version.
Still using an older version of `JamesIves/github-pages-deploy-action` will generate some warning like in this run: https://github.com/rustwasm/wasm-pack/actions/runs/4032230808
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions-rs/toolchain@v1, actions/cache@v2, JamesIves/github-pages-deploy-action@4.1.4. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
The PR will get rid of those warnings for `JamesIves/github-pages-deploy-action`, because v4.4.1 uses …
=> Update JamesIves/github-pages-deploy-action in GHA workflow to v4.4.1

npm/package.json
A bin entry in a package.json has to be a local file and not a command to be linked by a package manager.
See https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bin
> To use this, supply a bin field in your package.json which is a map of command name to local file name.
this fixes #1248
=> fix: wasm-pack bin script entry

.github/workflows/test.yml, .gitignore, Cargo.lock, Cargo.toml, src/install/krate.rs, src/lib.rs, src/manifest/mod.rs, src/test/webdriver.rs, src/test/webdriver/chromedriver.rs, src/test/webdriver/geckodriver.rs, tests/all/download.rs
The HTTP client is now pure Rust. This fixes a segfault I was having on my computer
Fixes https://github.com/rustwasm/wasm-pack/issues/1281
Fixes https://github.com/rustwasm/wasm-pack/issues/1234
Fixes https://github.com/rustwasm/wasm-pack/issues/1203
Fixes https://github.com/rustwasm/wasm-pack/issues/1079
Fixes https://github.com/rustwasm/wasm-pack/issues/997
Fixes https://github.com/rustwasm/wasm-pack/issues/650
Fixes https://github.com/rustwasm/wasm-pack/issues/823
```bash
```
=> Replace curl with ureq

docs/_installer/index.html, docs/_installer/wasm-pack.js, docs/public/custom.css
- First, show only the instructions specific to the detected platform.
- Then, always display the cargo, npm, and yarn install options below.
- Add a note to the unix instructions to say you can use the alternative options if you don't like piping `curl` into `sh`.
Fixes #355
*nix:
Unknown platform:
Windows:
=> Don't hide install options behind link

.github/workflows/book.yml, .github/workflows/release.yml, .github/workflows/test.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/rustwasm/wasm-pack/actions/runs/4460089878:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).
=> Replace unmaintained actions-rs/toolchain action in CI workflows

src/command/login.rs, src/command/mod.rs, src/npm.rs
`npm login` doesn't support `--always-auth` anymore, instead it is under the [`adduser` subcommand][1].
[1]: https://docs.npmjs.com/cli/v6/commands/npm-adduser#always-auth
```bash
```
- [-] You reference which issue is being closed in the PR text
=> fix: removes `--always-auth` from `npm login`

tests/all/utils/fixture.rs
Without this, some tests fail if Cargo prints any colors in its output.
````console
$ CARGO_TERM_COLOR=always cargo test --all --locked
...
failures:
---- log_level::log_level_error stdout ----
Created fixture at /git/tmp/wasm-pack/target/t/.tmpOZ8y7e/wasm-pack
thread 'log_level::log_level_error' panicked at 'Unexpected stderr, failed ((var.contains(Finished release [optimized] target(s) in ) && (! var.contains([WARN]: ⚠️   origin crate has no README))) && (! (((((var.contains([INFO]: 🎯  Checking for the Wasm target...) && var.contains([INFO]: 🌀  Compiling to Wasm...)) && var.contains([INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory)) && var.contains([INFO]: Optimizing wasm binaries with `wasm-opt`...)) && …
```
=> Turn off cargo colors during log level test

src/command/build.rs, src/manifest/mod.rs, src/readme.rs, tests/all/readme.rs
Fixes #1215 by honoring how package.readme is authored in Cargo.toml, if authored. This could be a path or a boolean to disable searching for the path.
Also fixes the existing `it_copies_a_readme_provided_path` test which was an exact copy - just with fewer empty lines - of `it_copies_a_readme_default_path` and wasn't honoring any authored path since there was no way to get the authored path.
=> Respect package.readme in Cargo.toml

CHANGELOG.md, docs/src/cargo-toml-configuration.md, src/bindgen.rs, src/manifest/mod.rs
There is currently no option to run `wasm-bindgen` with `--omit_default_module_path`.
This is relevant for projects that run in a context where usage of `input = new URL('file.wasm', import.meta.url);` is [causing problems](https://github.com/vitejs/vite/issues/5087) (e.g., in web workers).
This PR adds the option to run `wasm-bindgen` with `--omit_default_module_path`.
Reference: https://rustwasm.github.io/wasm-bindgen/reference/cli.html?highlight=omit#--omit-default-module-path
=> Add wasmbindgen option: `omit_default_module_path`

src/bindgen.rs, tests/all/build.rs
Fixes #1278
The bug was caused by using [binary_search](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.binary_search) on `extra_options` which is not sorted.
=> Fix getting the target-dir in wasm_bindgen_build

src/command/build.rs, src/command/mod.rs, src/command/test.rs, src/lib.rs, src/main.rs, src/manifest/mod.rs, src/readme.rs, tests/all/readme.rs
=> Revert "Respect package.readme in Cargo.toml" 

src/lib.rs
Fixes #1301, which was introduced by 73e059f754948ecd794a3809953bc5d49b93dce4.
It prints `wasm-pack 0.12.0`, just like wasm-pack 0.11.0 printed `wasm-pack 0.11.0`. That is to say: clap 4 formats the version the same way as structopt. It also adds the same `-V` short alias that structopt does.
=> Restore --version command

src/command/mod.rs, src/command/test.rs
A value parser for `OsString` cannot parse a command line argument for `Option<PathBuf>`, which let it failed to specify paths for `pack`, `publish` and `test` commands, which was introduced by https://github.com/rustwasm/wasm-pack/commit/73e059f754948ecd794a3809953bc5d49b93dce4.
close #1304.
```bash
$ ./target/debug/wasm-pack publish abc
thread 'main' panicked at 'Mismatch between definition and access of `path`. Could not downcast to std::path::PathBuf, need to downcast to std::ffi::os_str::OsString
', src/command/mod.rs:74:15
```
```bash
```
=> Fix value parser for `Option<PathBuf>`

src/build/wasm_target.rs
Rewritten wasm_target to use target libdir from the rustc tool rather than looking through sysroot.  This is to accomodate non-rustup installations.
Fixes [bug-1342](https://github.com/rustwasm/wasm-pack/issues/1342) 
Can clean up unused sysroot stuff too in this module if that's appropriate.  Just wanted someone to agree with this before I put anymore work into it.
```bash
```
=> Rewrite wasm_target to use target-libdir

src/test/webdriver/chromedriver.rs
fix https://github.com/rustwasm/wasm-pack/issues/1315.
I have tested it on my windows11 x86 pc, but not tested on macOS machines since I don't have one.
New endpoint changes target `mac64` to `mac-x64`
```rs
let target = if target::LINUX && target::x86_64 {
"linux64"
} else if target::MACOS && target::x86_64 {
"mac-x64" // here!
} else if target::MACOS && target::aarch64 {
"mac-arm64"
}
```
And that new endpoint provides chromedriver for `mac-arm64`:
```rs
let target = if target::LINUX && target::x86_64 {
"linux64"
} else if target::MACOS && target::x86_64 {
"mac-x64"
} else if target::MACOS && target::aarch64 {
"mac-arm64" // here!
}
```
=> Use new chromdriver endpoint

docs/_installer/init.sh
- Fixed error on line 139 - "==" was being used, whereas sh expects a "=" (and we do this correctly throughout the rest of the file). See https://www.shellcheck.net/wiki/SC3014 for more.
- Changed the use of backticks to the use of `$()` as specified in https://www.shellcheck.net/wiki/SC2006
- Changed the use of `-a` to `&&` as specified in https://www.shellcheck.net/wiki/SC2166
Closes #1159 
Closes #1217
Closes #1283
```bash
```
=> Fix error and warnings in install script

npm/binary.js
Closes #1354
Closes #1359
This PR fixes the NPM package's platform detection for mingw.
=> Add mingw support to npm package

src/command/build.rs
I am currently running `wasm-pack` three times for our project. Once for the main-thread wasm file, once for the web-worker wasm file, and once to generate types that include both of those builds.
This `--no-opt` option would help me immensely by reducing our build time by ~30% by not having to wait for the `wasm-opt` step for the type generation. I cannot disable `wasm-opt` generally in `Cargo.toml`, because I still want it for the other two actual build steps.
An alternative to this PR would be a `--types-only` option, which _only_ outputs a .d.ts file.
=> Add option to skip optimization with wasm-opt

src/command/mod.rs, src/command/pack.rs, src/command/publish/mod.rs, src/command/utils.rs
To be able to use these commands when the output directory option to the build command isn't the default pkg.
Resolves #1369
```bash
```
=> pkg-dir option for pack and publish commands

docs/src/commands/build.md
emm...
> Outputs JS that can be natively imported as an ES module in deno.
Is this description correct?
=> Docs: Add a description of `build --target deno` 

.github/workflows/test.yml, src/test/webdriver/chromedriver.rs, tests/all/log_level.rs
This fixes a few things to get CI working for the repo again:
- The chromedriver releases were previously 404ing, causing these tests to fail. The URL for where these are hosted was changed, so it's just a simple update to get this working again.
- In later Cargo releases, the output format for the "Finished..." log line changed. I've fixed this by making `matches_cargo` accept both the old and new formats.
- With MacOS 14 (and by extension, M1) runners becoming the `macos-latest` default, the current geckodriver setup fails for that platform. ~It's not entirely obvious to me why at this point. Downgrading to the `macos-13` runner has these tests working again. This is probably the most.. questionable change as it'd be better to track down why the latest runners don't work.~ Edit: It …
=> fix: update chromedriver download URL, resolve test issues

docs/src/tutorials/npm-browser-packages/index.md
Reduces number of steps taken backwards to reach the correct page of prerequisites
```bash
```
This PR closes #1386
=> Fix local navigation backing one step too far

src/test/webdriver/geckodriver.rs, tests/all/webdriver.rs
```bash
```
- [-] You reference which issue is being closed in the PR text
Introduces support to download Geckodriver in Linux `aarch64` based on artifacts available 
in Mozilla's releases: https://github.com/mozilla/geckodriver/releases.
=> feat(webdriver): support geckodriver for `linux-aarch64`

Cargo.lock, Cargo.toml, src/command/build.rs
```bash
```
close: https://github.com/rustwasm/wasm-pack/issues/1395
```
wasm-pack build --out-dir=../fib-wasm/wasm
```
Optimize out-dir display, from  
```
[INFO]: 📦   Your wasm pkg is ready to publish at /root/code/fib-wasm/fib-rs/../fib-wasm/wasm.
```
to
```
[INFO]: 📦   Your wasm pkg is ready to publish at /root/code/fib-wasm/fib-wasm/wasm.
```
I'm not sure if the clean function needs to be called in other places where the display function is called, it seems that just optimizing the display of out-dir is enough
=> fix: optimize out-dir display (close: #1395)

src/install/mod.rs
Closes #1392 
```bash
```
- [✅] You ran `cargo fmt` on the code base before submitting
- [✅] You reference which issue is being closed in the PR text
=> Implement wasm-opt linux aarch64 condition

docs/src/quickstart.md
Looks like about 15k other devs ran into the same issue as me:
https://stackoverflow.com/a/64342488/11950764
And the MDN article includes `--target web` in their instructions: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_Wasm
So I figured that these instructions should also have that flag.
I also added an extra dot point below the `build` dot point which briefly indicates how to use the built package.
Thanks!
=> Add `--target web` to quick start build command

Cargo.lock, Cargo.toml
=> chore: Update binary-install to v0.4.1

npm/binary.js
The version of the NPM [`binary-install`](https://www.npmjs.com/package/binary-install) package that `wasm-pack` uses stores binaries at an unversioned path in the `binary-install` package's directory.
This silently prevents version upgrades, as when upgrading to a different version of `wasm-pack`, `binary-install` believes the `wasm-pack` binary is already installed, and keeps using the old one. For example, upgrading the NPM `wasm-pack` package from `0.12.1` to `0.13.0` will continue using the `0.12.1` binary, and so has no effect (likely without the user noticing).
This moves the install directory to `node_modules/wasm-pack/binary/`, which should fix the issue.
=> fix: allow npm binary upgrades

Cargo.lock, Cargo.toml, src/installer.rs, src/main.rs
As per https://github.com/softprops/atty/issues/57#issuecomment-2367878741 we can just use the stdlib functionality that exists in Rust 1.70
=> chore: Remove unmaintained dependency atty in favor of stdlib

docs/src/cargo-toml-configuration.md, src/bindgen.rs, src/manifest/mod.rs
=> feat: allow bindgen-cli --split-linked-modules #1092

docs/src/cargo-toml-configuration.md, src/install/mod.rs
Closes #1422
This PR explicitly specifies the available wasm-opt optimization flags for extreme optimization cases.
```bash
```
=> Be more explicit with available wasm-opt flags in documentation

docs/_installer/init.sh
The wasm-pack installer script fails in CI environments with the error:
./install.sh: line 18: VERSION: unbound variable
This occurs when running the standard installation command:
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
The script uses 'set -u' on line 16, which causes bash to exit on undefined variables. Line 18 then references $VERSION before it's defined:
UPDATE_ROOT="https://github.com/rustwasm/wasm-pack/releases/download/$VERSION"
The script expects VERSION to be set as an environment variable, but this is not documented and is impractical in many CI environments where the command is piped directly to sh.
- GitHub Actions
- GitLab CI
- Jenkins
- Any environment where setting env vars before piping is difficult
This commit adds proper VERSION handling: …
=> fix: Handle undefined VERSION in installer script
