drager/wasm-pack

.travis.yml, Cargo.toml, src/lib.rs
=> feat(pkg): support license, repo

src/main.rs
Spotted a typo; should fix it. Thanks!
=> fix typo in Pack cmd

src/lib.rs
Figured adding documentation to a project is never a bad idea, so here's a PR documenting all the current methods, haha :sparkles:
- document the one method that's being exported
=> document write_package_json

examples/js-hello-world/Cargo.toml, examples/js-hello-world/src/lib.rs, src/lib.rs, src/main.rs, tests/wasm-pack.rs
=> add js-hello-world example and take a path as an arg

.gitignore, .travis.yml, README.md, examples/js-hello-world/Cargo.lock, src/bindgen.rs, src/build.rs, src/lib.rs, src/main.rs, tests/wasm-pack.rs
fixes #10 
~blocked by https://github.com/ashleygwilliams/wasm-pack/issues/16 at the moment~
=> feature: cargo/wasm-bindgen build step

src/main.rs
=> feat(msg): mark pack and publish as not implemented

.appveyor.yml, README.md
=> feat(test): add appveyor

Cargo.lock, Cargo.toml, tests/fixtures/package-json/package.json, tests/wasm-pack.rs
Tests a full directory, rather than a single file. Ref: https://github.com/ashleygwilliams/wasm-pack/issues/18#issuecomment-370895435. Thanks!
=> add dir_diff test

Cargo.lock, Cargo.toml, examples/js-hello-world/README.md, src/lib.rs, src/main.rs, src/manifest.rs, src/readme.rs, tests/fixtures/package-json/package.json, tests/manifest.rs, tests/readme.rs
=> feat(readme): copy from crate

examples/js-hello-world/Cargo.lock, examples/js-hello-world/Cargo.toml, examples/js-hello-world/src/lib.rs
=> fix: adding wasm-bindgen version rather than git repo

README.md
=> fix(doc): update readme code example

tests/manifest.rs, tests/utils/mod.rs
=> feat(test): test package json values

examples/no-readme/Cargo.lock, examples/no-readme/Cargo.toml, examples/no-readme/src/lib.rs, src/bindgen.rs, src/build.rs, src/emoji.rs, src/lib.rs, src/main.rs, src/manifest.rs, src/readme.rs
=> feat(readme): warn on no readme

README.md, src/main.rs, src/manifest.rs, tests/fixtures/scopes/Cargo.lock, tests/fixtures/scopes/Cargo.toml, tests/fixtures/scopes/README.md, tests/fixtures/scopes/src/lib.rs, tests/manifest/main.rs
=> mgattozzi scopes rollup

.gitignore, src/bindgen.rs, src/build.rs, src/lib.rs, src/manifest.rs, src/readme.rs
=> Yoshuawuyts collabs

README.md, src/bindgen.rs, src/build.rs, src/lib.rs, src/main.rs, src/manifest.rs, src/npm.rs, src/readme.rs
=> init pack and publish

README.md, tests/fixtures/js-hello-world/Cargo.toml, tests/fixtures/js-hello-world/src/lib.rs, tests/fixtures/no-readme/Cargo.toml, tests/fixtures/no-readme/src/lib.rs, tests/fixtures/scopes/Cargo.toml, tests/fixtures/scopes/src/lib.rs
=> update to wasm bindgen 0.2.0

.github/PULL_REQUEST_TEMPLATE.md
We want to make sure people format their code as well as reference the
issue that's going to be closed as well so we don't have to close the
issue manually! This PR adds a template for PRs that includes these
points as a checklist to ensure future contributors know what they need
to do!
=> Add PR template to the repo

CODE_OF_CONDUCT.md, CONTRIBUTING.md
=> Data pup add rustfmt instructions

src/bindgen.rs
=> feat(bindgen): use --force

Cargo.toml
Closes #148. Snatching this one while it's hot.
=> Add WASM to Cargo categories

README.md, docs/contributing.md
=> doc(readme): clean up readme and move some stuff to docs dir

src/build.rs, src/emoji.rs
=> Add nightly toolchain to commands

src/bindgen.rs, src/build.rs, src/command.rs, src/command/init.rs, src/command/login.rs, src/command/mod.rs, src/command/pack.rs, src/command/publish.rs, src/command/utils.rs, src/error.rs, src/manifest.rs, src/progressbar.rs, src/readme.rs, tests/manifest/main.rs
=> Let the spinners spin again

README.md
Best contribution ever <3.
```bash
```
=> doc(readme) Fix markup

src/manifest.rs, tests/manifest/main.rs
Reverts rustwasm/wasm-pack#197
=> Revert "fix(mainfest): missing _bg.js file in package.json"

.travis.yml
Until we have proper synchronization for test fixtures.
=> CI: Temporarily run tests with only one thread

.appveyor.yml, README.md
=> fix(badge): fix appveyor

Cargo.lock, README.md, tests/fixtures/bad-cargo-toml/src/lib.rs, tests/fixtures/js-hello-world/src/lib.rs, tests/fixtures/no-compile/src/lib.rs, tests/fixtures/no-readme/src/lib.rs, tests/fixtures/scopes/src/lib.rs
=> fix(tests): udpate fixtures for new rust feature flags

src/manifest.rs, tests/fixtures/serde-feature/Cargo.toml, tests/fixtures/serde-feature/README.md, tests/fixtures/serde-feature/src/lib.rs, tests/manifest/main.rs
=> fix(depcheck): don't fail on dep map

README.md, tests/fixtures/bad-cargo-toml/src/lib.rs, tests/fixtures/js-hello-world/src/lib.rs, tests/fixtures/no-compile/src/lib.rs, tests/fixtures/no-readme/src/lib.rs, tests/fixtures/scopes/src/lib.rs, tests/fixtures/serde-feature/src/lib.rs
=> And then there was one feature flag

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
cloned directory set to nightly~~ **Not applicable**
---
Fixes #206 
Issue Select | Bug Report | Feature Request
--- | --- | ---
=> Issue #206: create issue templates

src/build.rs
=> feat(build): force lib build only

docs/index.html, docs/installer/index.html
=> fix(homepage): links need wasm-pack URL segment

docs/index.html
=> fix(homepage): add wasm-pack segment to install button URL

README.md
=> chore(readme): clean up

docs/src/project-setup/manual-setup.md
=> [docs] Close quotes in cargo.toml example in manual setup

docs/src/prerequisites/index.md, docs/src/tutorial/index.md, docs/src/tutorial/template-deep-dive/src-utils-rs.md
Fixing some broken links and added some more Rust color highlighting. Should fix #513.
=> doc: Fix links and Rust highlightning

Cargo.lock, tests/all/bindgen.rs, tests/all/build.rs, tests/all/lockfile.rs, tests/all/test.rs, tests/all/utils/fixture.rs
=> Huangjj27 update bindgen version

tests/all/utils/fixture.rs
This fixes an accidental regression from #554 which was in turn an
accidental regression from #526
=> Fix tests on master

docs/src/command/pack-and-publish.md
=> fix(docs): remove extraneous docs src

docs/src/SUMMARY.md
=> fix(doc): add test to SUMMARY

README.md
=> fix(doc): remove init and add test to commands in README

src/build.rs, src/command/build.rs, src/command/test.rs
=> Drager non rustup env

docs/index.html
=> fix(homepage): show 0.6.1 til 0.7.0 is actually ready

README.md
=> fix(test): travis badge org -> com

README.md
=> feat(doc): add crates.io badge to readme

src/command/build.rs, src/command/mod.rs, src/command/publish/mod.rs
=> #640 minus changelog

src/manifest/mod.rs, src/manifest/npm/esmodules.rs, tests/all/manifest.rs, tests/all/utils/manifest.rs
#649 without the test update commit because the test failure seems spurious
=> #649 without the test update commit

src/manifest/mod.rs
=> fix(license): don't warn if license-file is present

README.md
=> Fix broken quickstart guide link

docs/src/commands/build.md
=> Update reference to cargo's `--offline` feature

RELEASE_CHECKLIST.md
@ashleygwilliams - let me know if I'm missing anything here?
=> Adds npm steps to release checklist

src/bindgen.rs, src/command/build.rs, src/command/test.rs, src/generate.rs, src/install/mod.rs, src/install/tool.rs, src/wasm_opt.rs, tests/all/download.rs, tests/all/utils/fixture.rs
=> refactor(tool): wasm-opt is a tool variant

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/index.html, npm/package-lock.json, npm/package.json
Reverts rustwasm/wasm-pack#786
ok looks like the local failure for me was that wasm-pack updated my chrome driver (v80) before my chrome (v79) updated.
@steveklabnik ran on windows and has no errors
=> Revert "Revert "0.9.1""

src/manifest/mod.rs, tests/all/build.rs
Closes https://github.com/rustwasm/wasm-pack/issues/829
```bash
```
=> Find the main package if multiple packages have the same name

docs/src/commands/new.md, docs/src/tutorials/npm-browser-packages/using-your-library.md
=> Add link to template repo

docs/src/tutorials/npm-browser-packages/template-deep-dive/src-utils-rs.md
~- [ ] You have the latest version of `rustfmt` installed~
```bash
```
~- [ ] You ran `cargo fmt` on the code base before submitting~
~- [ ] You reference which issue is being closed in the PR text~
=> [doc] fix toc links

.github/workflows/book.yml, .github/workflows/test.yml
=> chore(ci): Add build and deploy book

.github/workflows/release.yml
=> fix(ci): Upload window init exe file

docs/src/prerequisites/considerations.md
This PR fixes a spelling error in `considerations.md`, in the docs.
=> fix(typo): considerations.md

src/wasm_opt.rs
Fixes #1247.
I changed `find_wasm_opt` to return the path directly instead of an `install::Status`, and also handle the logging of messages about `wasm-opt` being skipped since the caller no longer has access to the `install::Status` to know what happened.
=> Fix discovery of locally installed `wasm-opt`

src/install/krate.rs
=> Add HTTP header USER-AGENT

src/bindgen.rs, src/build/mod.rs, src/command/build.rs, src/manifest/mod.rs, tests/all/build.rs, tests/all/utils/fixture.rs
Solves https://github.com/rustwasm/wasm-pack/issues/1111
```bash
```
=> feat: Implements custom build profile (closes #1111)
